'use client';
import {useState} from 'react';

const modes=['DA VERIFICARE','LIVE','LIVE SU BASE','PLAYBACK','BASE/REGISTRATA'];
const uses=['SF','PP','Musica protagonista','Sigla','Jingle','Stacco'];

export default function Home(){
 const [program,setProgram]=useState(''); const [date,setDate]=useState(''); const [results,setResults]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [selected,setSelected]=useState<any>(null);
 const [rows,setRows]=useState<any[]>([]);
 async function search(){setLoading(true); setSelected(null); const r=await fetch('/api/raiplay-search?q='+encodeURIComponent(program+(date?' '+date:''))); const j=await r.json(); setResults(j.results||[]); setLoading(false);}
 function add(){setRows([...rows,{in:'00:00:00.00',out:'00:00:00.00',dur:'',title:'',author:'',artist:'',use:'SF',mode:'DA VERIFICARE',confidence:'Candidato'}]);}
 function update(i:number,k:string,v:string){setRows(rows.map((r,n)=>n===i?{...r,[k]:v}:r));}
 function csv(){const h=['TC IN','TC OUT','Durata','Titolo','Autore','Interprete','Utilizzo','Modalità','Confidence']; const body=rows.map(r=>[r.in,r.out,r.dur,r.title,r.author,r.artist,r.use,r.mode,r.confidence]); const s=[h,...body].map(a=>a.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='rapporto_artistico.csv';a.click();}
 return <main><header><div className="logo">🎼 <b>Music Report AI</b></div><span>ACTARUSLAB</span></header><section className="hero"><p className="eyebrow">AI ASSISTANT FOR TV MUSIC REPORTING</p><h1>Da un titolo.<br/><em>Al rapporto artistico.</em></h1><p className="lead">Inserisci programma e data. L'app cerca automaticamente le pagine pubbliche RaiPlay e prepara la puntata per l'analisi.</p><div className="search"><input value={program} onChange={e=>setProgram(e.target.value)} placeholder="Titolo programma — es. Domenica In"/><input value={date} onChange={e=>setDate(e.target.value)} placeholder="Data — facoltativa"/><button onClick={search} disabled={!program||loading}>{loading?'RICERCA…':'🔎 CERCA SU RAIPLAY'}</button></div></section>
 {results.length>0&&<section className="panel"><h2>Puntate trovate</h2>{results.map((r,i)=><div className="result" key={i}><div><b>{r.title}</b><small>{r.url}</small></div><div><a href={r.url} target="_blank">Apri ↗</a><button onClick={()=>{setSelected(r);add()}}>PREPARA RAPPORTO</button></div></div>)}</section>}
 {selected&&<section className="panel"><div className="panelhead"><div><p className="eyebrow">PUNTATA SELEZIONATA</p><h2>{selected.title}</h2></div><span className="status">SORGENTE TROVATA</span></div><div className="notice">La ricerca della puntata è reale. L'analisi audiovisiva automatica richiede una sorgente video che l'utente/ente abbia diritto di elaborare; l'app non aggira DRM o autenticazioni.</div><h2>Rapporto artistico</h2><div className="tablewrap"><table><thead><tr>{['TC IN','TC OUT','Durata','Titolo','Autore','Interprete','Utilizzo','Modalità','Confidence'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{['in','out','dur','title','author','artist'].map(k=><td key={k}><input value={r[k]} onChange={e=>update(i,k,e.target.value)}/></td>)}<td><select value={r.use} onChange={e=>update(i,'use',e.target.value)}>{uses.map(x=><option key={x}>{x}</option>)}</select></td><td><select value={r.mode} onChange={e=>update(i,'mode',e.target.value)}>{modes.map(x=><option key={x}>{x}</option>)}</select></td><td><select value={r.confidence} onChange={e=>update(i,'confidence',e.target.value)}>{['Candidato','Alta','Media','Bassa','Confermato'].map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></div><div className="actions"><button onClick={add}>＋ AGGIUNGI RIGA</button><button onClick={csv}>⬇ ESPORTA CSV</button></div></section>}
 <footer>Music Report AI · ActarusLab · Prototype v0.1</footer></main>;
}