'use client';
import {useState} from 'react';

const modes=['DA VERIFICARE','LIVE','LIVE SU BASE','PLAYBACK','BASE/REGISTRATA'];
const uses=['SF','PP','Musica protagonista','Sigla','Jingle','Stacco'];
const blank=()=>({in:'00:00:00.00',out:'00:00:00.00',dur:'',title:'',author:'',artist:'',use:'SF',mode:'DA VERIFICARE',confidence:'Candidato'});

function flatten(v:any): any[] { const out:any[]=[]; const walk=(x:any)=>{if(!x)return;if(Array.isArray(x))return x.forEach(walk);if(typeof x!=='object')return;out.push(x);Object.values(x).forEach(walk)};walk(v);return out; }

export default function Home(){
 const [program,setProgram]=useState(''); const [date,setDate]=useState(''); const [results,setResults]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [selected,setSelected]=useState<any>(null); const [metadata,setMetadata]=useState<any>(null); const [analyzing,setAnalyzing]=useState(false); const [rows,setRows]=useState<any[]>([]); const [message,setMessage]=useState('');
 async function search(){setLoading(true);setMessage('');setSelected(null);setMetadata(null);try{const r=await fetch('/api/raiplay-search?q='+encodeURIComponent(program)+'&date='+encodeURIComponent(date));const j=await r.json();setResults(j.results||[]);if(!(j.results||[]).length)setMessage('Nessuna corrispondenza trovata. Prova titolo + data precisa.');}catch{setMessage('Ricerca non disponibile.')}finally{setLoading(false)}}
 async function prepare(r:any){setSelected(r);setAnalyzing(true);setRows([]);setMessage('');try{const x=await fetch('/api/raiplay-program?url='+encodeURIComponent(r.url));const j=await x.json();setMetadata(j.data||null);const objects=flatten(j.data);const videos=objects.filter(o=>o.video||o.hasVideo||o.duration||o.durata);const generated=videos.slice(0,50).map((o:any)=>({in:'',out:'',dur:String(o.duration||o.durata||''),title:String(o.name||o.title||o.titolo||''),author:String(o.author||o.autore||''),artist:String(o.artist||o.interprete||''),use:'SF',mode:'DA VERIFICARE',confidence:'Candidato'}));setRows(generated.length?generated:[blank()]);}catch{setRows([blank()]);}finally{setAnalyzing(false)}}
 function add(){setRows([...rows,blank()]);}
 function update(i:number,k:string,v:string){setRows(rows.map((r,n)=>n===i?{...r,[k]:v}:r));}
 function csv(){const h=['TC IN','TC OUT','Durata','Titolo','Autore','Interprete','Utilizzo','Modalità','Confidence'];const body=rows.map(r=>[r.in,r.out,r.dur,r.title,r.author,r.artist,r.use,r.mode,r.confidence]);const s=[h,...body].map(a=>a.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='rapporto_artistico.csv';a.click();}
 return <main><header><div className="logo">🎼 <b>Music Report AI</b></div><span>ACTARUSLAB · PRIVATO</span></header><section className="hero"><p className="eyebrow">AI ASSISTANT FOR TV MUSIC REPORTING</p><h1>Da un titolo.<br/><em>Al rapporto artistico.</em></h1><p className="lead">Inserisci programma e data. L'app cerca RaiPlay, individua la sorgente pubblica e prepara automaticamente la scheda di lavoro.</p><div className="search"><input value={program} onChange={e=>setProgram(e.target.value)} placeholder="Titolo programma — es. Domenica In"/><input value={date} onChange={e=>setDate(e.target.value)} placeholder="Data — es. 11/09/2026"/><button onClick={search} disabled={!program||loading}>{loading?'RICERCA…':'🔎 CERCA'}</button></div>{message&&<div className="notice">{message}</div>}</section>
 {results.length>0&&<section className="panel"><div className="panelhead"><h2>Risultati RaiPlay</h2><span className="status">{results.length} RISULTATI</span></div>{results.map((r,i)=><div className="result" key={i}><div><b>{r.title}</b><small>{r.url}</small></div><div><a href={r.url} target="_blank">Apri ↗</a><button onClick={()=>prepare(r)}>ANALIZZA</button></div></div>)}</section>}
 {selected&&<section className="panel"><div className="panelhead"><div><p className="eyebrow">PUNTATA SELEZIONATA</p><h2>{selected.title}</h2></div><span className="status">{analyzing?'ANALISI METADATI…':'SORGENTE TROVATA'}</span></div>{metadata&&<div className="metadata"><b>Metadati RaiPlay acquisiti.</b> La tabella sotto è precompilata dove il catalogo espone informazioni strutturate. I campi musicali non presenti restano da verificare durante l'ascolto.</div>}<div className="notice">Per l'analisi audio/video automatica completa serve una sorgente che tu o l'ente abbiate diritto di elaborare. L'app non aggira DRM o autenticazioni.</div><h2>Rapporto artistico</h2><div className="tablewrap"><table><thead><tr>{['TC IN','TC OUT','Durata','Titolo','Autore','Interprete','Utilizzo','Modalità','Confidence'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{['in','out','dur','title','author','artist'].map(k=><td key={k}><input value={r[k]} onChange={e=>update(i,k,e.target.value)}/></td>)}<td><select value={r.use} onChange={e=>update(i,'use',e.target.value)}>{uses.map(x=><option key={x}>{x}</option>)}</select></td><td><select value={r.mode} onChange={e=>update(i,'mode',e.target.value)}>{modes.map(x=><option key={x}>{x}</option>)}</select></td><td><select value={r.confidence} onChange={e=>update(i,'confidence',e.target.value)}>{['Candidato','Alta','Media','Bassa','Confermato'].map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></div><div className="actions"><button onClick={add}>＋ AGGIUNGI RIGA</button><button onClick={csv}>⬇ ESPORTA CSV</button></div></section>}
 <footer>Music Report AI · ActarusLab · v0.2 · uso personale</footer></main>;
}
